### ISSUE TITLE
Morphology oriented vs. Syntax oriented tags

### ISSUE THREAD

**Issue by Andres-Chandia** [unimorph/unimorph#7]
Hi there,
I've been trying to figure out how to move my set of tags to the standardized one you propose...
I have started converting "-IV" and "-TV" (intransitive and transitive verb tags) to "VERB", but already at this point I've realized that you give this tag to the entire form, to its (syntactic) function (inside a phrase or sentence), while the tags I'm using are oriented not to the function but to the form of the word, which is what I'm intending to reflect.
For instance, a verb in Mapudüngun may be derived from a noun, or the the stem may be a compound involving a noun and a verb roots, for example, so I need to tag those noun and verb:
pewmatukefuyiñ
`-NN.pewma-TV.tu-CR.TV+CF.ke14+IPD.fu8+IND.y4+1.Ø3+PL.iñ2`
'We used to dream (about things)'

Unimorph tagging would render something like:
`VERB;CF;IPD;IND;1;PL`

Approximately, probably some tags would be different, the point is that the information about some components forming the word, actually the stem, are not reflected...

I am not criticizing your work, I'm just exposing this to you in order to ask if you know how should I handle it with the purpose of obtaining analyses like the ones I already have but with standardized tags?

I hope I'm expressing myself clear enough, sorry if I don't, I will try to clarify any point you ask about...

Thanks in advance for your support!!

**Comment by aryamccarthy** [comment]
UniMorph is intended to convey universal semantics.

Segmentation-based analyses that assign features to spans of the word are described in the paper introducing UniMorph 3.0.

**Comment by Andres-Chandia** [comment]
Thanks for your quick answer...
you mean this document: [Sylak-Glassman (2016)](https://unimorph.github.io/doc/unimorph-schema.pdf)?

**Comment by aryamccarthy** [comment]
I mean this one: [UniMorph 3.0: Universal Morphology](https://aclanthology.org/2020.lrec-1.483/).

**Comment by Andres-Chandia** [comment]
Thanks a lot again!

**Comment by Andres-Chandia** [comment]
Hi again Arya, a question and I don't bother you again... (at least not in a good while -sorry-)
Would you say that this is a standard way of tagging the previous example I gave?

düngupeyüm: `-NN.pewma-TV.tu-CR.TV+CF.ke14+IPD.fu8+IND.y4+1.Ø3+PL.iñ2`

UniMorph: `N;V|TR;HAB;-PFV;IND;1;P`

It could be derived from this tagging that there is a "noun (root)" followed by "transitive verb (root)"?
Is there a way to indicate that these two previous elements form a compound which is the stem of the entire verbal form?
And then, following the stem, there is an "habitual" suffix, then an "antiperfective"?
And finally, this part I think is clear..., an "indicative" suffix followed by a "1st person" suffix and a "plural" suffix at the end of the verbal form.
Would that be an appropriate way to tag?

**Note**: the "-CR.TV" tag indicates that the stem formed by a compound ended up being "Transitive", this is probably not necessary at the end... I have to think about it because in Mapudüngun compound stems behave like this:
```
AnyPoS+TR.VERB = TR.Stem
AnyPoS+INTR.VERB = INTR.Stem
TR.VERB+AnyPoS = TR.Stem
INTR.VERB+AnyPoS = INTR.Stem
TR.VERB+TR.VERB = TR.Stem
INTR.VERB+INTR.VERB = INTR.Stem
```
but:
```
TR.VERB+INTR.VERB = INTR.Stem
INTR.VERB+TR.VERB = TR.Stem
```
